pretrained_model_path: "/data/weights/stable_diffusion/stable_diffusion_v15"
output_dir: "./outputs/xray-of-hands"

train_data:
  data_mode: "images"
  images_path: "data/xray-of-hands"
  prompt: "xray of hands"
  n_sample_frames: 24
  width: 288
  height: 288
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "xray of legs"
    - "hands waving"
    - "xray of hands waving"
    - "xray of body running"
  video_length: 24
  width: 288
  height: 288
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False
